Add missing semicolon
I'm unable to build this flake because of the following error:
```
❯ nix profile install git+https://github.com/nwg-piotr/nwg-displays
error: syntax error, unexpected '=', expecting ';'

       at /nix/store/cx2p7mqzx7jl4r33g4ywgqnny1b142m9-source/flake.nix:3:10:

            2|   description = "An output management utility for the sway Wayland compositor, inspired by wdisplays and wlay."
            3|   inputs = {
             |          ^
            4|     nixpkgs.url = "github:nixos/nixpkgs/nixos-unstable";
```